### ISSUE TITLE
Idea: Cloud support

### ISSUE THREAD

**Issue by vanitasvitae** [stevesoltys/seedvault#12]
Hi!
In the FDroid forums, I [came up with the idea](https://forum.f-droid.org/t/app-idea-cloud-backup-provider/4805) to extend the `BackupTransport` API for cloud backups to selfhosted clouds like Nextcloud.

I'm very pleased to see, that extending the API is indeed possible, as proven by this project.
It would be super awesome, if this project would at some point support adding cloud servers (Nextcloud, Owncloud, Seafile...) as storage backend.

What do you think? :)

**Comment by stevesoltys** [comment]
Hey! Yes, I think this makes sense. I designed the app in a way that should allow for easy configuration of storage backends if they are implemented.

However, it actually might be possible to do this already, since the app uses a content provider: https://developer.android.com/guide/topics/providers/content-providers

This of course means that the target cloud provider needs to allow you to save via content provider in their mobile app.

**Comment by grote** [comment]
Once https://github.com/nextcloud/android/pull/3905 is merged and released, we'll have cloud support.

**Comment by vanitasvitae** [comment]
@grote @stevesoltys it is so nice that you took up the work :)

**Comment by stevesoltys** [comment]
Closing since we now have Nextcloud support.
