### ISSUE TITLE
Add support for bundling application APKs

### ISSUE THREAD

**Issue by stevesoltys** [stevesoltys/seedvault#18]
The application should allow users to select APKs to back up / restore.

**Comment by grote** [comment]
Potential issues with this:
* larger backup size, needs different quota handling
* higher bandwidth requirements
* leaks which apps you use to storage location (difficult to reliably obfuscate/hide)

**Comment by beerisgood** [comment]
Maybe just a info about missing apps in this case and only backup / restore the data ?

**Comment by grote** [comment]
It seems to be impossible to restore data for apps that are not installed.

**Comment by thrdroom** [comment]
> Potential issues with this:
> 
>     * larger backup size, needs different quota handling
> 
>     * higher bandwidth requirements
> 
>     * leaks which apps you use to storage location (difficult to reliably obfuscate/hide)

Never the less, **The application should allow users to select APKs to back up / restore!**
Applicationdata only is **NOT ENOUGH** for a proper Backup-tool imho.

**Comment by grote** [comment]
Another option is to ask the app stores to re-install the apps before restoring their data. Upstream tickets:
* [F-Droid](https://gitlab.com/fdroid/fdroidclient/issues/1546)
* [Aurora](https://gitlab.com/AuroraOSS/AuroraStore/issues/171)

**Comment by stevesoltys** [comment]
Ideally, we would go with @grote's suggestion to be able to provide the functionality without overhead.

The only issue I can think of would be for applications that don't exist in those app stores, or for users who want a certain version of the app restored. In the worst case, the functionality could be optional.

How do Google cloud backups currently handle this?

**Comment by grote** [comment]
> How do Google cloud backups currently handle this?

Finding this out would be a great easy contribution to the project without the need for coding skills. Same applies if an app was installed with a different signature than the Google Play version of the app. Both could be tested in one run.

**Comment by thrdroom** [comment]
> Another option is to ask the app stores to re-install the apps before restoring their data. Upstream tickets:
> 
>     * [F-Droid](https://gitlab.com/fdroid/fdroidclient/issues/1546)
> 
>     * [Aurora](https://gitlab.com/AuroraOSS/AuroraStore/issues/171)

This is not enough, cause a backup should be a thing of "complete or nothing"...only app data is just a half-ass backup. What if i want to do a restore but google decided they delete the app(apk), or i dont have internet access or need to save my bandwith but need to do a restore on the go? What if i also want to backup/restore apps installed from source other than the playstore or fdroid? Please dont ditch the idea of a proper full backup solution, or this app will be the next android "backup"-thing that never made it and faded away in the wind.

**Comment by thrdroom** [comment]
> How do Google cloud backups currently handle this?

Googles cloud backup should not be the measurement here feature wise...your app should be better than what googles cloud backup has to offer!

**Comment by grote** [comment]
> Please dont ditch the idea of a proper full backup solution

How do you suggest to hide the apps you use from the backup server?

> Googles cloud backup should not be the measurement here feature wise...

How they do stuff still matters, because they implement the same AOSP backup API (which Titanium btw. doesn't and thus doesn't compare).

> For a real "full backup" you should also consider an "force backup" option for rooted users

This is its own feature request, not relevant to this ticket and IMHO out of scope for this app which root users don't need. It also would require modifying the OS itself.

**Comment by stevesoltys** [comment]
Like @grote suggested, a priority for this application is privacy, so hiding the apps being backed up by default would be most important here. I do understand your concern @thrdroom, and it does make sense - I brought up the same issues you mentioned.

If no good solution can be found which solves both problems, backing up the APK files along with the backups could be optional for the user at the cost of privacy.

Again, we should find out how this is handled with the proprietary backups first, since Google likely thought of the same scenarios we're discussing.

**Comment by grote** [comment]
> backing up the APK files along with the backups could be optional for the user at the cost of privacy.

If the user uses flash drives or storage with its own end-to-end encryption (Nextcloud has this in beta), then there wouldn't be a big privacy cost.

**Comment by grote** [comment]
Let's assume we do provide an option to also back up APKs (maybe exposed as a setting) for those who either don't care about the privacy implications or back up to a storage where they don't matter
(removable storage or one with additional client-side encryption). How would we do it?

Let me try to sketch out a plan:

### Backup

When APK backups are enabled and we are told to back up an app by the system, we
* check if the app is a system app   ([`FLAG_SYSTEM`](https://developer.android.com/reference/android/content/pm/ApplicationInfo.html#FLAG_SYSTEM)) and don't do anything in that case (or should we also back up when `FLAG_UPDATED_SYSTEM_APP` is set?)
* check if we can access the APK ([`ApplicationInfo#sourceDir`](https://developer.android.com/reference/android/content/pm/ApplicationInfo.html#sourceDir))
* check if we have metadata available for this app (maybe in Seedvault's internal [`SharedPreferences`](https://developer.android.com/reference/android/content/SharedPreferences) or a file in its data dir) and create it if missing

The metadata could be a JSON object with package names as keys and one JSON object per package:

```json
{
        "@meta@": {
                "version": 0,
                "token": 157608344,
                "sdk_int": 29,
                "name": "Google Pixel 2 XL",
                "incremental": "2019.09.18.13"
        },
        "org.example": {
                "version_code": 123,
                "time": 1576083447000,
                "installer_package_name": "org.fdroid.fdroid",
                "signatures": [
                        "5c887cdf2f14c56b8a5020718d27410f66754d65c37867d3848269145bf1ab16",
                        "b72e3674ab2cf75c0345ad890eb7ece121e00dba82f8a05e05887aaccb21638b"
                ]
        }
}
```

The first entry isn't really a package, but a metadata key to store things like the version of the backup app to allow future versions read old backup formats.

* if no metadata was available, we write the APK (unencrypted for now) to the backup storage,
  add the app's metadata and write out the encrypted metadata file (in overwrite mode) to the storage as well. Only when that was sucessful, we update our internal cache of the metadata.
* if metadata was available, we check:
  * if the version code stored is equal or higher than that of the installed app and the signatures have not changed, then we don't do anything
  * if the version code stored is lower than that of the installed app or the signatures have changed, then we write out the newer APK and update the metadata as above.
* then we continue with the normal app data backup process and pray that we do not run into the timeout set by the OS.

### Restore

* after the user has chosen a RestoreSet, we save the restore token and close the RestoreSession again
* we read our metadata file from backup storage and check that:
  * one of the APK's signatures (sha256 hash) is in the stored signatures
  * the APK's version code matches the stored version code
* Then we install all APKs that have valid metadata
* once all APKs have been installed, we set their installer package name
* now we ask the system for a full restore

**Comment by chirayudesai** [comment]
Sounds good for the most part.

Some things

Backup:
* Let's backup updated system apps to match the behaviour of adb backup
* Metadata looks good, should be it's own json file in the app's `Context.getFilesDir()`.
* Consider backing up widget data
* Consider backing up obbs (though file sizes might skyrocket)
* The thing about praying that all of this happens before the timeout - we should try to make that solid. How does ADB Backup handle it, does it set a higher timeout? Wwe should try doing the same here if that's what it's going to take.
Also, I guess with the timeout a lot of it might go into uploading the data especially if backing up a bigger APK to a cloud document provider, am I correct in assuming that?

Restore:
* What about auto restore? Would it interfere when the backed up APKs are installed?
* Consider restoring widget data and obbs
* Do we have to wait for restoring till all apps are installed? It would be better UX to have an app data starting to get restored the moment it is restored, so that we don't hit the case where App A has been installed but since we're still waiting for B-Z we don't have it's data restored, but the user sees it installed and tries to use it anyway.
I understand that there might be a delay anyway between installing an app and restoring it's data, but it should be a lot smaller than waiting for all apks to be installed.
How does ADB Backup handle this?

ADB backup supports backing up APKs, but that may be going away.
However, as of AOSP 10 that code is still present, and thus we can try to do things in the same way they are while we can.
Can check `AppMetadataBackupWriter` and `FullBackupEngine` in AOSP frameworks/base to get an idea.

**Comment by grote** [comment]
> Let's backup updated system apps to match the behaviour of adb backup
> Metadata looks good, should be it's own json file in the app's Context.getFilesDir().

Sounds good. I edited the post above accordingly.

> Consider backing up widget data

This should already be done by AOSP.

> Consider backing up obbs (though file sizes might skyrocket)

Yeah I don't really feel like doing it, at least not in the first pass. Also, I think I never ever had an app that needed obbs.

> The thing about praying that all of this happens before the timeout - we should try to make that solid.

So far I just found something about backup agent timeouts in the code and am not sure if this also relates to the transport. The lowest default value there is 30 seconds for a K/V backup. I suggest to just try this and if we run into timeouts, instead of increasing them (we never know how slow  network connection can be) my suggestions is to separate the APK backup runs from the system's backup runs and schedule those ourselves.

> What about auto restore? Would it interfere when the backed up APKs are installed?

I don't see how. Auto-restore just restores app data after an app was installed. This is handled by the system. We are just asked if we have data for that app. If yes, we supply it to the system. Whether or not we also backed up an APK for that app shouldn't matter. Do you have a specific hunch on what could be interfering?

> Do we have to wait for restoring till all apps are installed?

Strictly not, but it is the safer approach. It should be possible to later change this to interleave installs and restores without introducing breaking changes.

> so that we don't hit the case where App A has been installed but since we're still waiting for B-Z we don't have it's data restored, but the user sees it installed and tries to use it anyway.

That shouldn't happen as we block progress in the SetupWizard until the restore is complete. Considering that, there isn't much advantage of interleaving installs and restores. Though, it could still be done later to liberate the user earlier and let apps pop up after the user finalized the SetupWizard.

This reminds me that *if* backup was enabled during SetupWizard and our transport selected, installing apps *could* already trigger auto-restore. So we would only need to restore all packages that do not have corresponding APKs first, then liberate the user and then start installing backed up APKs. Still, I prefer to start as simple as possible in the first iteration.

> However, as of AOSP 10 that code is still present, and thus we can try to do things in the same way they are while we can.

There's also comments such as 

> `Fix or remove apk and obb implementation (only used for adb).`

which suggests that the code is broken, but sure we can look at it to make sure we are not missing anything. Personally, I would prefer to have a simpler implementation. Also, we should make sure to change SeedVault's license to Apache2 since we were looking at Apache2 code a lot ;)

**Comment by chirayudesai** [comment]
> > Let's backup updated system apps to match the behaviour of adb backup
> > Metadata looks good, should be it's own json file in the app's Context.getFilesDir().
> 
> Sounds good. I edited the post above accordingly.
> 
> > Consider backing up widget data
> 
> This should already be done by AOSP.
> 
> > Consider backing up obbs (though file sizes might skyrocket)
> 
> Yeah I don't really feel like doing it, at least not in the first pass. Also, I think I never ever had an app that needed obbs.
Well, sure, we don't have to do it now, but it would still be good to have sometime.
I have exactly one obb on my device right now, it's a game, that's what they're generally used for.
> 
> > The thing about praying that all of this happens before the timeout - we should try to make that solid.
> 
> So far I just found something about backup agent timeouts in the code and am not sure if this also relates to the transport. The lowest default value there is 30 seconds for a K/V backup. I suggest to just try this and if we run into timeouts, instead of increasing them (we never know how slow network connection can be) my suggestions is to separate the APK backup runs from the system's backup runs and schedule those ourselves.

Separating the runs could lead to incosistenencies though, which would be a lot worse than just having longer timeouts if needed.
> 
> > What about auto restore? Would it interfere when the backed up APKs are installed?
> 
> I don't see how. Auto-restore just restores app data after an app was installed. This is handled by the system. We are just asked if we have data for that app. If yes, we supply it to the system. Whether or not we also backed up an APK for that app shouldn't matter. Do you have a specific hunch on what could be interfering?
So, during restore, we install an apk. Right after that, the system asks us if we have data for that app, what do we say? That is what I meant here.
Whether or not we back up an APK for that app matters here because I'm only trying to ask a question about that case, and not general auto-restore usage.
> 
> > Do we have to wait for restoring till all apps are installed?
> 
> Strictly not, but it is the safer approach. It should be possible to later change this to interleave installs and restores without introducing breaking changes.
How is it safer?
> 
> > so that we don't hit the case where App A has been installed but since we're still waiting for B-Z we don't have it's data restored, but the user sees it installed and tries to use it anyway.
> 
> That shouldn't happen as we block progress in the SetupWizard until the restore is complete. Considering that, there isn't much advantage of interleaving installs and restores. Though, it could still be done later to liberate the user earlier and let apps pop up after the user finalized the SetupWizard.
Ah right, good point.
But yeah, later on if we could just restore apps and their data one by one, being able to use the device much earlier.
> 
> This reminds me that _if_ backup was enabled during SetupWizard and our transport selected, installing apps _could_ already trigger auto-restore. So we would only need to restore all packages that do not have corresponding APKs first, then liberate the user and then start installing backed up APKs. Still, I prefer to start as simple as possible in the first iteration.
Exactly, this would be the best!
On restore, while still in Setupwizard we restore system apps and settings
Then, fire off a job to install apps one by one, and like you said, the system would trigger auto-restore and get their data from us.
I like simple as well, but this does not really seem that complicated given a lot of the heavy lifting would be done by the system.
> 
> > However, as of AOSP 10 that code is still present, and thus we can try to do things in the same way they are while we can.
> 
> There's also comments such as
> 
> > `Fix or remove apk and obb implementation (only used for adb).`
> 
> which suggests that the code is broken, but sure we can look at it to make sure we are not missing anything. Personally, I would prefer to have a simpler implementation. Also, we should make sure to change SeedVault's license to Apache2 since we were looking at Apache2 code a lot ;)

The point isn't to use the code as-is, I never said that.
What I said was we can try to do things in the same way as they are, like we already are with the metadata.

Let's not get into licensing here, and we do not have to change the entire app's license just to use some Apache2 snippets if needed. This should be discussed on a separate issue if it's a concern.

**Comment by grote** [comment]
Something we haven't really considered so far is that Google is pushing apps to use [App Bundle](https://developer.android.com/platform/technology/app-bundle) which is a new distribution format which is specific to the device in question. We would need to test what happens when we try to restore such an app on another device.

There's also Instant Apps and OBBs.

For now, we can start with classic APKs.

**Comment by chirayudesai** [comment]
Aurora does support installing split APKs so that can be used for testing. We could try to create a list of some popular apps using App Bundles and try them across different configurations (devices, emulator configs, etc) and then we can figure out how exactly to deal with them.

Instant Apps: Same, need to test.

OBBs: Much simpler I think, since those are just files being copied to a particular directory for the most part, so it could potentially be handled in #57 


Starting with classic APKs sounds good, and we can add the above as we encounter them and lay out a brief plan.

**Comment by grote** [comment]
@stevesoltys can we close this now? Maybe open dedicated tickets for possible enhancements discussed in this ticket?
