### ISSUE TITLE
"App Doesn't Allow Backup"

### ISSUE THREAD

**Issue by CrafterLaughter** [stevesoltys/seedvault#81]
Brilliant project.  Thanks for all your efforts!

I just applied the GrapheneOS stable branch update that went live today and did a backup.  Seedvault returns "App doesn't allow backup" for 29 apps.  Having skimmed through the existing github submissions I came across https://github.com/stevesoltys/seedvault/issues/65#issuecomment-573086814

Correct me if I'm mistaken.  I gather the metadata info just hasn't been merged into master at least for the GrapheneOS version?

Can you please illuminate a little more if apps are allowed to set a "no backup" flag that Seedvault respects?

If not, will Seedvault give a means override the skipping of these app backups?  I just ask because I was previously used to TWRP/Titanium Backup to get back up and running quickly.

If it were possible to backup and restore all internal storage that would be great also.

Though adb backup is deprecated, I was hearing it worked for some folks.  Tried it with my Pixel 2 handsets.  Unfortunately no luck with that.

Edit: I just went to transfer the SeedVault backup folder to my PC and see that ALL apks appear to have been backed up.  Stellar!  My guess is I'm just not seeing the following backup error flags as mentioned in that other thread.

APK_OPT_OUT when an app opts out of backup, but we got its APK
APK_ABOVE_QUOTA when an app is above the quota, but we got its APK
APK_ERROR when an app has a backup error, but got its APK

**Comment by stevesoltys** [comment]
Hey! Android applications are allowed to opt-out of backups: https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup

Seedvault respects this because it is an AOSP feature - for good reason. Some applications opt out because they consider the data to be sensitive and/or the user should be able to re-create that data in another way.

If applications are opting out of backups and they shouldn't be, it's up to the app developers to resolve that issue.

The APKs may be there, but the application data for those applications will not be included in the backup. So, the apps should be re-installed during a restore, but they won't have any data.

The internal storage ticket is https://github.com/stevesoltys/seedvault/issues/57.

**Comment by CrafterLaughter** [comment]
Great info.  I went ahead an subscribed to https://github.com/stevesoltys/seedvault/issues/57  
Cheers!

**Comment by onpars** [comment]
> Hey! Android applications are allowed to opt-out of backups: https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup
> 
> Seedvault respects this because it is an AOSP feature - for good reason. Some applications opt out because they consider the data to be sensitive and/or the user should be able to re-create that data in another way.
> 
> If applications are opting out of backups and they shouldn't be, it's up to the app developers to resolve that issue.

What the application developer wants should be considered as a friendly request. The user should be presented with the appropriate warnings. However, these are user devices. It should be the user who should have ultimate control over what the device should do and what not.

Users should have the right to extract all information which was created on, stored on their devices. Even if they have to click through scary warnings. Even if in secure. Perhaps it's just for testing purposes, auditing applications (looking if these violate privacy), security research or any purpose.

Could you please consider adding a configuration option which would allow ignoring applications requesting not to be backup?

There is a war on general computation.

https://www.youtube.com/watch?v=HUEvRyemKSg

Could you please consider looking that topic up and joining the side of "users should be in control" instead of "others should be in control"?

**Comment by neckcen** [comment]
I'd tend to agree with onpars on this one. I just started using seedvault after upgrading to lineage 17 and was disappointed to discover that the majority of my apps are, in fact, not backed up: only 5 apps allow backups on the whole device. The irony is that most of the "unbackupable" apps have some sort of backup or export mechanism of their own, often not automated and much less secure than what seedvault has to offer.

I believe most developers use the "disable backup" settings quite liberally, whether to promote their own solution or in fear of google's own backup system. In practice my backup will be encrypted on the phone's filesystem (which is encrypted itself). It will then be transmitted in little encrypted chunks (syncthing) over the network to be stored (still encrypted) on the encrypted filesystem of a server I own and to which only a few select people have physical access. I do not believe any application to offer a better or safer solution.

**Comment by grote** [comment]
> Could you please consider adding a configuration option which would allow ignoring applications requesting not to be backup?

We can't override this without patching the OS which we don't control.

> Users should have the right to extract all information which was created on, stored on their devices. 

Luckily Android (AOSP) is Free Software, so you are in control and patch this out with a one-liner. But this is OS level and not related to Seedvault.

There's #165, but it doesn't work as advertised.

**Comment by neckcen** [comment]
It makes sense for it to be enforced at the OS level or it would be rather pointless. But it pretty much means that any backup done through the official API is at best partial and at worse useless. Guess it's still titanium on a rooted device if one wants a true backup.

Regardless, thank you for the explanation.

**Comment by ghost** [comment]
> What the application developer wants should be considered as a friendly request. The user should be presented with the appropriate warnings. However, these are user devices. It should be the user who should have ultimate control over what the device should do and what not.
> 
> Users should have the right to extract all information which was created on, stored on their devices. Even if they have to click through scary warnings. Even if in secure. Perhaps it's just for testing purposes, auditing applications (looking if these violate privacy), security research or any purpose.
> 
> Could you please consider adding a configuration option which would allow ignoring applications requesting not to be backup?
> 
> There is a war on general computation.
> 
> https://www.youtube.com/watch?v=HUEvRyemKSg
> 
> Could you please consider looking that topic up and joining the side of "users should be in control" instead of "others should be in control"?

This.
Agree over9000%.
Pissed off so much by those disrespectful software devs who don't offer user choice and decide something about my device and my data on my device instead of ME. These devs should rather switch over to developing something for Apple or Crapdows 10/11, they would feel like home over there. :smile: 
And by the AOSP devs too, for allowing software devs to do so and adding this "App doesn't allow backup" thing to the OS at all.
The final choice is to be up to the user, and no one else.

Really hope that Seedvault devs can find a workaround for this and add "ignore App doesn't allow backup" option some day in the future :slightly_smiling_face:
